### ISSUE TITLE
Empty lists in retrieving drainage basis

### ISSUE THREAD

**Issue by facusapienza21** [ICESAT-2HackWeek/CloudMask#8]
In `krigMaskNorth.ipynb`, after converting `LL` to a list, this seems to be an empty list and that is the source of the error.

<img width="1119" alt="Screen Shot 2020-10-02 at 9 55 21 PM" src="https://user-images.githubusercontent.com/39526081/95276882-c6135c80-0822-11eb-9c1f-51f3bc38ba16.png">

**Comment by espg** [comment]
Hey @facusapienza21 , I'm having trouble replicating this-- I don't get an empty list on my end:
![image](https://user-images.githubusercontent.com/3896161/95925671-a70f5000-0d77-11eb-9ad2-0f567de8f2ee.png)

I'm using python3, so I'm not sure what the issue is... you are executing the line that reads `zwally`, right? Is that variable empty?

**Comment by espg** [comment]
perhaps it's an environment issue? This is the `default.nix` declaration that I'm using to build pandas and the rest:

```
with import <nixpkgs> {};

stdenv.mkDerivation rec {
  name = "env" ;
  builder = builtins.toFile "builder.sh" ''
    source $stdenv/setup; ln-s $env $out
  '';

  buildInputs = [ python36 git geos proj mkl
    (python36.buildEnv.override {
      ignoreCollisions = true;
      extraLibs = with python36Packages; [
        (numpy.override {blas = mkl ;})
        mkl-service
	rasterio
        scipy
        matplotlib
        joblib
        tqdm
        geopandas
        pillow
        pyproj
        pip
        jupyter
        boto3
        cython
        seaborn
        gdal
        click
      ];
     })
    ];

shellHook = ''
    alias pip="PIP_PREFIX='$(pwd)/_build/pip_packages' \pip"
    export PYTHONPATH="$(pwd)/_build/pip_packages/lib/python3.6/site-packages:$PYTHONPATH"
    export GEOS_DIR="/nix/store/7fq3pykybqcfzki9bqzhgypl1fhpf2xb-geos-3.6.3"
    unset SOURCE_DATE_EPOCH
'';}
```

**Comment by facusapienza21** [comment]
Thank you @espg for your answer! I am not sure if it is an environment issue, I am using all those packages. I am not sure if I am using the `zwally` right, but this is what I have:

<img width="1035" alt="Screen Shot 2020-10-17 at 3 19 32 PM" src="https://user-images.githubusercontent.com/39526081/96350510-82bfb600-108c-11eb-9b9d-6c9a1656e6dc.png">

Something weird: I notice that in the `basin` column here the basis are integer numbers, so when I put `basin = 6` now at least I get a list with something inside: 

<img width="1050" alt="Screen Shot 2020-10-17 at 3 19 50 PM" src="https://user-images.githubusercontent.com/39526081/96350533-ba2e6280-108c-11eb-8030-550f4c80632d.png">

**Comment by espg** [comment]
@facusapienza21 sorry for being slow on this... the screenshot helps a lot. It looks like pandas is not being very consistent in how it's reading the textfile. Here's what `zwally` looks like for me after doing `read_csv`: 

![image](https://user-images.githubusercontent.com/3896161/97397274-7ddddc00-18ae-11eb-9c4e-1e43aabcefec.png)

...the issue looks like a parser issue? Not sure why the separator flag is seen differently in your code... `sep='\s*'` should be parse on whitespace (tab or space), of arbitrary contiguous lengths... but for your case, it looks like it's interpreting white space between each character, instead of as three columns. I think you can set the number of columns manually; you just shouldn't have to, it should be smart enough to infer it, and I'm not sure why it can't. What's even weirder is that it isn't even assigning the first part of the data as a column; it looks like it's trying to almost set it as an index? Or that just going into basin as a sequence/series?

**Comment by facusapienza21** [comment]
Great! I just solved it. I don't know why in my version of the notebook I had `sep = \s*`, but after I changed to `sep = \s+` it worked:

<img width="1043" alt="Screen Shot 2020-11-02 at 1 15 54 AM" src="https://user-images.githubusercontent.com/39526081/97829568-32aa3b80-1ca9-11eb-9537-0c889c89036d.png">

Thank you @espg !
